### ISSUE TITLE
ローカルで使えるパッケージマネージャー

### ISSUE THREAD

**Issue by musaprg** [musaprg/xsvr-tools#1]
みたいなの作りたい（あったらそれを使えばいい）

**Comment by ta2gch** [comment]
こんにちは。TANIGUCHI と申します。
pkgbrewというソフトウェアを開発しております。
もしまだ開発されていなければお使い下さい。
https://github.com/ta2gch/pkgbrew
なお、類似プロジェクトとして

- guix
- pkgsrc
- linuxbrew

などがございます。お力になれれば幸いです。

**Comment by musaprg** [comment]
@ta2gch なんと…！素晴らしいです！ありがたく使わさせていただきます… :+1:
